# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Cache Go modules
      uses: actions/cache@v4
      with:
        path: |
          ~/go/pkg/mod
          ~/.cache/go-build
        key: ${{ runner.os }}-go-${{ hashFiles('src/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: 'src/go.mod'
        cache: false
      env:
        GO111MODULE: on
        GOMODCACHE: ~/go/pkg/mod

    - name: Verify go.sum exists
      run: ls -la src/

    - name: Download dependencies
      working-directory: src
      run: go mod download

    - name: Build
      working-directory: src
      run: go build -v ./...

    - name: Test
      working-directory: src
      run: go test -v ./...
